// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Orisia.Server.Data;

#nullable disable

namespace Orisia.Server.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
partial class ApplicationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.5")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Orisia.Server.Data.Entities.Event", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<bool>("AllDay")
                .HasColumnType("boolean");

            b.Property<Guid?>("CoverMediaId")
                .HasColumnType("uuid");

            b.Property<DateTime>("CreatedOn")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("DescriptionBg")
                .IsRequired()
                .HasColumnType("text");

            b.Property<string>("DescriptionEn")
                .IsRequired()
                .HasColumnType("text");

            b.Property<DateTime?>("EndAt")
                .HasColumnType("timestamp with time zone");

            b.Property<int>("EventType")
                .HasColumnType("integer");

            b.Property<bool>("Featured")
                .HasColumnType("boolean");

            b.Property<bool>("IsDeleted")
                .HasColumnType("boolean");

            b.Property<string>("Location")
                .HasMaxLength(300)
                .HasColumnType("character varying(300)");

            b.Property<DateTime>("ModifiedOn")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("RecurrenceRule")
                .HasMaxLength(500)
                .HasColumnType("character varying(500)");

            b.Property<string>("Slug")
                .IsRequired()
                .HasMaxLength(180)
                .HasColumnType("character varying(180)");

            b.Property<DateTime>("StartAt")
                .HasColumnType("timestamp with time zone");

            b.Property<int>("Status")
                .HasColumnType("integer");

            b.Property<string>("TitleBg")
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnType("character varying(250)");

            b.Property<string>("TitleEn")
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnType("character varying(250)");

            b.HasKey("Id");

            b.HasIndex("EventType", "Status", "StartAt");

            b.HasIndex("Featured", "Status", "StartAt");

            b.HasIndex("Slug")
                .IsUnique()
                .HasFilter("\"IsDeleted\" = false");

            b.HasIndex("Status", "StartAt");

            b.ToTable("Events");
        });

        modelBuilder.Entity("Orisia.Server.Data.Entities.Post", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<Guid?>("AuthorId")
                .HasColumnType("uuid");

            b.Property<string>("BodyBg")
                .IsRequired()
                .HasColumnType("text");

            b.Property<string>("BodyEn")
                .IsRequired()
                .HasColumnType("text");

            b.Property<Guid?>("CoverMediaId")
                .HasColumnType("uuid");

            b.Property<DateTime>("CreatedOn")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("ExcerptBg")
                .HasMaxLength(500)
                .HasColumnType("character varying(500)");

            b.Property<string>("ExcerptEn")
                .HasMaxLength(500)
                .HasColumnType("character varying(500)");

            b.Property<bool>("Featured")
                .HasColumnType("boolean");

            b.Property<bool>("IsDeleted")
                .HasColumnType("boolean");

            b.Property<DateTime>("ModifiedOn")
                .HasColumnType("timestamp with time zone");

            b.Property<DateTime?>("PublishedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("SeoDescriptionBg")
                .HasMaxLength(180)
                .HasColumnType("character varying(180)");

            b.Property<string>("SeoDescriptionEn")
                .HasMaxLength(180)
                .HasColumnType("character varying(180)");

            b.Property<string>("SeoTitleBg")
                .HasMaxLength(70)
                .HasColumnType("character varying(70)");

            b.Property<string>("SeoTitleEn")
                .HasMaxLength(70)
                .HasColumnType("character varying(70)");

            b.Property<string>("Slug")
                .IsRequired()
                .HasMaxLength(180)
                .HasColumnType("character varying(180)");

            b.Property<int>("Status")
                .HasColumnType("integer");

            b.Property<string>("TitleBg")
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnType("character varying(250)");

            b.Property<string>("TitleEn")
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnType("character varying(250)");

            b.Property<int>("Type")
                .HasColumnType("integer");

            b.HasKey("Id");

            b.HasIndex("AuthorId");

            b.HasIndex("Featured", "Status");

            b.HasIndex("Slug")
                .IsUnique()
                .HasFilter("\"IsDeleted\" = false");

            b.HasIndex("Type", "Status", "PublishedAt");

            b.ToTable("Posts");
        });

        modelBuilder.Entity("Orisia.Server.Data.Entities.User", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<DateTime>("CreatedOn")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Email")
                .IsRequired()
                .HasColumnType("text");

            b.Property<bool>("IsDeleted")
                .HasColumnType("boolean");

            b.Property<DateTime>("ModifiedOn")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Names")
                .IsRequired()
                .HasColumnType("text");

            b.Property<string>("PasswordHash")
                .IsRequired()
                .HasColumnType("text");

            b.Property<string>("Phone")
                .IsRequired()
                .HasColumnType("text");

            b.Property<string>("RefreshToken")
                .HasColumnType("text");

            b.Property<DateTime?>("RefreshTokenExpiryTime")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Role")
                .HasColumnType("text");

            b.HasKey("Id");

            b.ToTable("Users");
        });

        modelBuilder.Entity("Orisia.Server.Data.Entities.Post", b =>
        {
            b.HasOne("Orisia.Server.Data.Entities.User", "Author")
                .WithMany("Posts")
                .HasForeignKey("AuthorId")
                .OnDelete(DeleteBehavior.SetNull);

            b.Navigation("Author");
        });

        modelBuilder.Entity("Orisia.Server.Data.Entities.User", b =>
        {
            b.Navigation("Posts");
        });
#pragma warning restore 612, 618
    }
}
