// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Orisia.Server.Data;

#nullable disable

namespace Orisia.Server.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
partial class ApplicationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.5")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Orisia.Server.Data.Entities.Dance", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<bool>("Active")
                .HasColumnType("boolean");

            b.Property<DateTime>("CreatedOn")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("DescriptionBg")
                .IsRequired()
                .HasColumnType("text");

            b.Property<string>("DescriptionEn")
                .IsRequired()
                .HasColumnType("text");

            b.Property<int?>("DurationSeconds")
                .HasColumnType("integer");

            b.Property<bool>("IsDeleted")
                .HasColumnType("boolean");

            b.Property<DateTime>("ModifiedOn")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Region")
                .HasMaxLength(120)
                .HasColumnType("character varying(120)");

            b.Property<string>("Rhythm")
                .HasMaxLength(120)
                .HasColumnType("character varying(120)");

            b.Property<string>("Slug")
                .IsRequired()
                .HasMaxLength(180)
                .HasColumnType("character varying(180)");

            b.Property<int>("SortOrder")
                .HasColumnType("integer");

            b.Property<Guid?>("ThumbnailMediaId")
                .HasColumnType("uuid");

            b.Property<string>("TitleBg")
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnType("character varying(250)");

            b.Property<string>("TitleEn")
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnType("character varying(250)");

            b.Property<string>("VideoUrl")
                .HasMaxLength(1000)
                .HasColumnType("character varying(1000)");

            b.HasKey("Id");

            b.HasIndex("Active", "SortOrder");

            b.HasIndex("Region");

            b.HasIndex("Slug")
                .IsUnique()
                .HasFilter("\"IsDeleted\" = false");

            b.HasIndex("ThumbnailMediaId");

            b.ToTable("Dances");
        });

        modelBuilder.Entity("Orisia.Server.Data.Entities.Event", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<bool>("AllDay")
                .HasColumnType("boolean");

            b.Property<Guid?>("CoverMediaId")
                .HasColumnType("uuid");

            b.Property<DateTime>("CreatedOn")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("DescriptionBg")
                .IsRequired()
                .HasColumnType("text");

            b.Property<string>("DescriptionEn")
                .IsRequired()
                .HasColumnType("text");

            b.Property<DateTime?>("EndAt")
                .HasColumnType("timestamp with time zone");

            b.Property<int>("EventType")
                .HasColumnType("integer");

            b.Property<bool>("Featured")
                .HasColumnType("boolean");

            b.Property<bool>("IsDeleted")
                .HasColumnType("boolean");

            b.Property<string>("Location")
                .HasMaxLength(300)
                .HasColumnType("character varying(300)");

            b.Property<DateTime>("ModifiedOn")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("RecurrenceRule")
                .HasMaxLength(500)
                .HasColumnType("character varying(500)");

            b.Property<string>("Slug")
                .IsRequired()
                .HasMaxLength(180)
                .HasColumnType("character varying(180)");

            b.Property<DateTime>("StartAt")
                .HasColumnType("timestamp with time zone");

            b.Property<int>("Status")
                .HasColumnType("integer");

            b.Property<string>("TitleBg")
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnType("character varying(250)");

            b.Property<string>("TitleEn")
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnType("character varying(250)");

            b.HasKey("Id");

            b.HasIndex("CoverMediaId");

            b.HasIndex("EventType", "Status", "StartAt");

            b.HasIndex("Featured", "Status", "StartAt");

            b.HasIndex("Slug")
                .IsUnique()
                .HasFilter("\"IsDeleted\" = false");

            b.HasIndex("Status", "StartAt");

            b.ToTable("Events");
        });

        modelBuilder.Entity("Orisia.Server.Data.Entities.GalleryAlbum", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<bool>("Active").HasColumnType("boolean");
            b.Property<Guid?>("CoverMediaId").HasColumnType("uuid");
            b.Property<DateTime>("CreatedOn").HasColumnType("timestamp with time zone");
            b.Property<string>("DescriptionBg").HasMaxLength(1000).HasColumnType("character varying(1000)");
            b.Property<string>("DescriptionEn").HasMaxLength(1000).HasColumnType("character varying(1000)");
            b.Property<bool>("Featured").HasColumnType("boolean");
            b.Property<bool>("IsDeleted").HasColumnType("boolean");
            b.Property<DateTime>("ModifiedOn").HasColumnType("timestamp with time zone");
            b.Property<string>("Slug").IsRequired().HasMaxLength(180).HasColumnType("character varying(180)");
            b.Property<int>("SortOrder").HasColumnType("integer");
            b.Property<string>("TitleBg").IsRequired().HasMaxLength(250).HasColumnType("character varying(250)");
            b.Property<string>("TitleEn").IsRequired().HasMaxLength(250).HasColumnType("character varying(250)");
            b.HasKey("Id");
            b.HasIndex("Active", "Featured", "SortOrder");
            b.HasIndex("CoverMediaId");
            b.HasIndex("Slug").IsUnique().HasFilter("\"IsDeleted\" = false");
            b.ToTable("GalleryAlbums");
        });

        modelBuilder.Entity("Orisia.Server.Data.Entities.GalleryMedia", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<bool>("Active").HasColumnType("boolean");
            b.Property<string>("CaptionBg").HasMaxLength(500).HasColumnType("character varying(500)");
            b.Property<string>("CaptionEn").HasMaxLength(500).HasColumnType("character varying(500)");
            b.Property<DateTime>("CreatedOn").HasColumnType("timestamp with time zone");
            b.Property<Guid>("GalleryAlbumId").HasColumnType("uuid");
            b.Property<bool>("IsDeleted").HasColumnType("boolean");
            b.Property<Guid>("MediaId").HasColumnType("uuid");
            b.Property<DateTime>("ModifiedOn").HasColumnType("timestamp with time zone");
            b.Property<int>("SortOrder").HasColumnType("integer");
            b.HasKey("Id");
            b.HasIndex("GalleryAlbumId", "MediaId").IsUnique().HasFilter("\"IsDeleted\" = false");
            b.HasIndex("GalleryAlbumId", "SortOrder");
            b.HasIndex("MediaId");
            b.ToTable("GalleryMedia");
        });

        modelBuilder.Entity("Orisia.Server.Data.Entities.Media", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<string>("AltBg")
                .HasMaxLength(300)
                .HasColumnType("character varying(300)");

            b.Property<string>("AltEn")
                .HasMaxLength(300)
                .HasColumnType("character varying(300)");

            b.Property<DateTime>("CreatedOn")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Extension")
                .IsRequired()
                .HasMaxLength(16)
                .HasColumnType("character varying(16)");

            b.Property<int>("Height")
                .HasColumnType("integer");

            b.Property<bool>("IsDeleted")
                .HasColumnType("boolean");

            b.Property<string>("MimeType")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)");

            b.Property<DateTime>("ModifiedOn")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("OriginalFileName")
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnType("character varying(255)");

            b.Property<string>("Sha256")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)");

            b.Property<long>("SizeBytes")
                .HasColumnType("bigint");

            b.Property<string>("StorageKey")
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnType("character varying(500)");

            b.Property<string>("ThumbnailStorageKey")
                .HasMaxLength(500)
                .HasColumnType("character varying(500)");

            b.Property<Guid?>("UploadedById")
                .HasColumnType("uuid");

            b.Property<int>("Width")
                .HasColumnType("integer");

            b.HasKey("Id");

            b.HasIndex("CreatedOn");

            b.HasIndex("Sha256");

            b.HasIndex("StorageKey")
                .IsUnique();

            b.HasIndex("UploadedById");

            b.ToTable("Media");
        });

        modelBuilder.Entity("Orisia.Server.Data.Entities.Post", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<Guid?>("AuthorId")
                .HasColumnType("uuid");

            b.Property<string>("BodyBg")
                .IsRequired()
                .HasColumnType("text");

            b.Property<string>("BodyEn")
                .IsRequired()
                .HasColumnType("text");

            b.Property<Guid?>("CoverMediaId")
                .HasColumnType("uuid");

            b.Property<DateTime>("CreatedOn")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("ExcerptBg")
                .HasMaxLength(500)
                .HasColumnType("character varying(500)");

            b.Property<string>("ExcerptEn")
                .HasMaxLength(500)
                .HasColumnType("character varying(500)");

            b.Property<bool>("Featured")
                .HasColumnType("boolean");

            b.Property<bool>("IsDeleted")
                .HasColumnType("boolean");

            b.Property<DateTime>("ModifiedOn")
                .HasColumnType("timestamp with time zone");

            b.Property<DateTime?>("PublishedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("SeoDescriptionBg")
                .HasMaxLength(180)
                .HasColumnType("character varying(180)");

            b.Property<string>("SeoDescriptionEn")
                .HasMaxLength(180)
                .HasColumnType("character varying(180)");

            b.Property<string>("SeoTitleBg")
                .HasMaxLength(70)
                .HasColumnType("character varying(70)");

            b.Property<string>("SeoTitleEn")
                .HasMaxLength(70)
                .HasColumnType("character varying(70)");

            b.Property<string>("Slug")
                .IsRequired()
                .HasMaxLength(180)
                .HasColumnType("character varying(180)");

            b.Property<int>("Status")
                .HasColumnType("integer");

            b.Property<string>("TitleBg")
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnType("character varying(250)");

            b.Property<string>("TitleEn")
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnType("character varying(250)");

            b.Property<int>("Type")
                .HasColumnType("integer");

            b.HasKey("Id");

            b.HasIndex("AuthorId");

            b.HasIndex("CoverMediaId");

            b.HasIndex("Featured", "Status");

            b.HasIndex("Slug")
                .IsUnique()
                .HasFilter("\"IsDeleted\" = false");

            b.HasIndex("Type", "Status", "PublishedAt");

            b.ToTable("Posts");
        });

        modelBuilder.Entity("Orisia.Server.Data.Entities.SiteReview", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<string>("AuthorName")
                .IsRequired()
                .HasMaxLength(120)
                .HasColumnType("character varying(120)");

            b.Property<string>("Content")
                .IsRequired()
                .HasMaxLength(2000)
                .HasColumnType("character varying(2000)");

            b.Property<DateTime>("CreatedOn")
                .HasColumnType("timestamp with time zone");

            b.Property<bool>("Featured")
                .HasColumnType("boolean");

            b.Property<bool>("IsDeleted")
                .HasColumnType("boolean");

            b.Property<DateTime?>("ModeratedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<Guid?>("ModeratedById")
                .HasColumnType("uuid");

            b.Property<DateTime>("ModifiedOn")
                .HasColumnType("timestamp with time zone");

            b.Property<int>("Rating")
                .HasColumnType("integer");

            b.Property<int>("Status")
                .HasColumnType("integer");

            b.Property<Guid?>("UserId")
                .HasColumnType("uuid");

            b.HasKey("Id");

            b.HasIndex("ModeratedById");

            b.HasIndex("Status", "Featured", "CreatedOn");

            b.HasIndex("UserId");

            b.ToTable("SiteReviews");
        });

        modelBuilder.Entity("Orisia.Server.Data.Entities.User", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<DateTime>("CreatedOn")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Email")
                .IsRequired()
                .HasColumnType("text");

            b.Property<bool>("IsDeleted")
                .HasColumnType("boolean");

            b.Property<DateTime>("ModifiedOn")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Names")
                .IsRequired()
                .HasColumnType("text");

            b.Property<string>("PasswordHash")
                .IsRequired()
                .HasColumnType("text");

            b.Property<string>("Phone")
                .IsRequired()
                .HasColumnType("text");

            b.Property<string>("RefreshToken")
                .HasColumnType("text");

            b.Property<DateTime?>("RefreshTokenExpiryTime")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Role")
                .HasColumnType("text");

            b.HasKey("Id");

            b.ToTable("Users");
        });

        modelBuilder.Entity("Orisia.Server.Data.Entities.Dance", b =>
        {
            b.HasOne("Orisia.Server.Data.Entities.Media", "ThumbnailMedia")
                .WithMany()
                .HasForeignKey("ThumbnailMediaId")
                .OnDelete(DeleteBehavior.SetNull);

            b.Navigation("ThumbnailMedia");
        });

        modelBuilder.Entity("Orisia.Server.Data.Entities.Event", b =>
        {
            b.HasOne("Orisia.Server.Data.Entities.Media", "CoverMedia")
                .WithMany()
                .HasForeignKey("CoverMediaId")
                .OnDelete(DeleteBehavior.SetNull);

            b.Navigation("CoverMedia");
        });

        modelBuilder.Entity("Orisia.Server.Data.Entities.GalleryAlbum", b =>
        {
            b.HasOne("Orisia.Server.Data.Entities.Media", "CoverMedia")
                .WithMany()
                .HasForeignKey("CoverMediaId")
                .OnDelete(DeleteBehavior.SetNull);

            b.Navigation("CoverMedia");
        });

        modelBuilder.Entity("Orisia.Server.Data.Entities.GalleryMedia", b =>
        {
            b.HasOne("Orisia.Server.Data.Entities.GalleryAlbum", "GalleryAlbum")
                .WithMany("Items")
                .HasForeignKey("GalleryAlbumId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.HasOne("Orisia.Server.Data.Entities.Media", "Media")
                .WithMany()
                .HasForeignKey("MediaId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.Navigation("GalleryAlbum");
            b.Navigation("Media");
        });

        modelBuilder.Entity("Orisia.Server.Data.Entities.Media", b =>
        {
            b.HasOne("Orisia.Server.Data.Entities.User", "UploadedBy")
                .WithMany("MediaUploads")
                .HasForeignKey("UploadedById")
                .OnDelete(DeleteBehavior.SetNull);

            b.Navigation("UploadedBy");
        });

        modelBuilder.Entity("Orisia.Server.Data.Entities.Post", b =>
        {
            b.HasOne("Orisia.Server.Data.Entities.User", "Author")
                .WithMany("Posts")
                .HasForeignKey("AuthorId")
                .OnDelete(DeleteBehavior.SetNull);

            b.HasOne("Orisia.Server.Data.Entities.Media", "CoverMedia")
                .WithMany()
                .HasForeignKey("CoverMediaId")
                .OnDelete(DeleteBehavior.SetNull);

            b.Navigation("Author");

            b.Navigation("CoverMedia");
        });

        modelBuilder.Entity("Orisia.Server.Data.Entities.SiteReview", b =>
        {
            b.HasOne("Orisia.Server.Data.Entities.User", "ModeratedBy")
                .WithMany()
                .HasForeignKey("ModeratedById")
                .OnDelete(DeleteBehavior.SetNull);

            b.HasOne("Orisia.Server.Data.Entities.User", "User")
                .WithMany("SiteReviews")
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.SetNull);

            b.Navigation("ModeratedBy");
            b.Navigation("User");
        });

        modelBuilder.Entity("Orisia.Server.Data.Entities.GalleryAlbum", b =>
        {
            b.Navigation("Items");
        });

        modelBuilder.Entity("Orisia.Server.Data.Entities.User", b =>
        {
            b.Navigation("MediaUploads");

            b.Navigation("Posts");

            b.Navigation("SiteReviews");
        });
#pragma warning restore 612, 618
    }
}
