<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Orisia.Server.Common\Orisia.Server.Common.csproj" />
    <ProjectReference Include="..\Orisia.Server.Core\Orisia.Server.Core.csproj" />
    <ProjectReference Include="..\Orisia.Server.Data\Orisia.Server.Data.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Orisia.Server.Domain</AssemblyName>
    <RootNamespace>Orisia.Server.Domain</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
